const ACTIONS = {
  GET_BOOKS: 'GET_BOOKS'
}

const MUTATIONS = {
  GET_BOOKS_REQUEST: 'GET_BOOKS_REQUEST',
  GET_BOOKS_SUCCESS: 'GET_BOOKS_SUCCESS',
  GET_BOOKS_FAILURE: 'GET_BOOKS_FAILURE'
}

export default {
  ACTIONS,
  MUTATIONS
}
